spring:
  application:
    name: omnia-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${DB_PORT:5432}/${DB:omniadb}}
    username: ${DB_USERNAME:omniauser}
    password: ${DB_PASSWORD:omniapass}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      # ddl-auto: update
      jdbc:
        lob:
          non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG

# security:
#   module:
#     jwt:
#       secret: ${JWT_SECRET}
#       expiration: 60
#       refresh-expiration: 1440
#     allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}
#     public-endpoints: /api/public/**,/api/auth/refresh
#     app-admin:
#       email: ${ADMIN_EMAIL}
#       password: ${ADMIN_PASSWORD}

cors:
  allowed:
    origins: ${ALLOWED_ORIGINS:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
